# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 599)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.yanguangyi = QtWidgets.QStackedWidget(self.centralwidget)
        self.yanguangyi.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.yanguangyi.setObjectName("yanguangyi")
        self.page_main_win = QtWidgets.QWidget()
        self.page_main_win.setObjectName("page_main_win")
        self.frame = QtWidgets.QFrame(self.page_main_win)
        self.frame.setGeometry(QtCore.QRect(0, 0, 941, 741))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_clear = QtWidgets.QPushButton(self.frame)
        self.pushButton_clear.setGeometry(QtCore.QRect(420, 544, 74, 54))
        self.pushButton_clear.setStyleSheet("background-image: url(:/toppage/icon/toppage/down/5.png);")
        self.pushButton_clear.setText("")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_set = QtWidgets.QPushButton(self.frame)
        self.pushButton_set.setGeometry(QtCore.QRect(110, 545, 74, 54))
        self.pushButton_set.setStyleSheet("background-image: url(:/toppage/icon/toppage/down/set.png);")
        self.pushButton_set.setText("")
        self.pushButton_set.setObjectName("pushButton_set")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(401, 6, 131, 51))
        self.comboBox_3.setStyleSheet("")
        self.comboBox_3.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.comboBox_3.setIconSize(QtCore.QSize(100, 40))
        self.comboBox_3.setFrame(False)
        self.comboBox_3.setObjectName("comboBox_3")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/12.0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/12.0.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/12.0.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox_3.addItem(icon, "")
        self.comboBox_3.setItemText(0, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/13.5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/13.5.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/13.5.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox_3.addItem(icon1, "")
        self.comboBox_3.setItemText(1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/15.0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/15.0.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/15.0.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox_3.addItem(icon2, "")
        self.comboBox_3.setItemText(2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/0.0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/0.0.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/0.0.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox_3.addItem(icon3, "")
        self.comboBox_3.setItemText(3, "")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(620, 544, 74, 54))
        self.pushButton_4.setStyleSheet("background-image: url(:/toppage/icon/toppage/down/2.png);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_show_pic = QtWidgets.QLabel(self.frame)
        self.label_show_pic.setGeometry(QtCore.QRect(80, 60, 640, 480))
        self.label_show_pic.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.label_show_pic.setText("")
        self.label_show_pic.setObjectName("label_show_pic")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(280, 6, 131, 51))
        self.comboBox_2.setStyleSheet("")
        self.comboBox_2.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.comboBox_2.setIconSize(QtCore.QSize(100, 40))
        self.comboBox_2.setFrame(False)
        self.comboBox_2.setObjectName("comboBox_2")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/+.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/+.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox_2.addItem(icon4, "")
        self.comboBox_2.setItemText(0, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/-.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/-.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox_2.addItem(icon5, "")
        self.comboBox_2.setItemText(1, "")
        self.pushButton_HIS = QtWidgets.QPushButton(self.frame)
        self.pushButton_HIS.setGeometry(QtCore.QRect(520, 544, 74, 54))
        self.pushButton_HIS.setStyleSheet("background-image: url(:/toppage/icon/toppage/down/6.png);")
        self.pushButton_HIS.setText("")
        self.pushButton_HIS.setObjectName("pushButton_HIS")
        self.pushButton_show_hateman = QtWidgets.QPushButton(self.frame)
        self.pushButton_show_hateman.setGeometry(QtCore.QRect(720, 544, 74, 54))
        self.pushButton_show_hateman.setStyleSheet("background-image: url(:/toppage/icon/toppage/down/3.png);")
        self.pushButton_show_hateman.setText("")
        self.pushButton_show_hateman.setObjectName("pushButton_show_hateman")
        self.label_L_R1 = QtWidgets.QLabel(self.frame)
        self.label_L_R1.setGeometry(QtCore.QRect(620, 270, 91, 20))
        self.label_L_R1.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_L_R1.setText("")
        self.label_L_R1.setObjectName("label_L_R1")
        self.label_L_R2 = QtWidgets.QLabel(self.frame)
        self.label_L_R2.setGeometry(QtCore.QRect(620, 320, 91, 20))
        self.label_L_R2.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_L_R2.setText("")
        self.label_L_R2.setObjectName("label_L_R2")
        self.label_L_Axis = QtWidgets.QLabel(self.frame)
        self.label_L_Axis.setGeometry(QtCore.QRect(610, 360, 101, 20))
        self.label_L_Axis.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_L_Axis.setText("")
        self.label_L_Axis.setObjectName("label_L_Axis")
        self.pushButton_R = QtWidgets.QPushButton(self.frame)
        self.pushButton_R.setGeometry(QtCore.QRect(10, 10, 58, 64))
        self.pushButton_R.setStyleSheet("background-image: url(:/toppage/icon/toppage/r.png);")
        self.pushButton_R.setText("")
        self.pushButton_R.setObjectName("pushButton_R")
        self.label_L_S = QtWidgets.QLabel(self.frame)
        self.label_L_S.setGeometry(QtCore.QRect(650, 130, 61, 16))
        self.label_L_S.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_L_S.setText("")
        self.label_L_S.setObjectName("label_L_S")
        self.label_L_C = QtWidgets.QLabel(self.frame)
        self.label_L_C.setGeometry(QtCore.QRect(650, 180, 61, 16))
        self.label_L_C.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_L_C.setText("")
        self.label_L_C.setObjectName("label_L_C")
        self.label_L_A = QtWidgets.QLabel(self.frame)
        self.label_L_A.setGeometry(QtCore.QRect(640, 230, 71, 20))
        self.label_L_A.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_L_A.setText("")
        self.label_L_A.setObjectName("label_L_A")
        self.label_R_A = QtWidgets.QLabel(self.frame)
        self.label_R_A.setGeometry(QtCore.QRect(90, 230, 71, 16))
        self.label_R_A.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_R_A.setText("")
        self.label_R_A.setObjectName("label_R_A")
        self.label_R_S = QtWidgets.QLabel(self.frame)
        self.label_R_S.setGeometry(QtCore.QRect(90, 130, 61, 16))
        self.label_R_S.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_R_S.setText("")
        self.label_R_S.setObjectName("label_R_S")
        self.label_R_C = QtWidgets.QLabel(self.frame)
        self.label_R_C.setGeometry(QtCore.QRect(90, 180, 61, 16))
        self.label_R_C.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_R_C.setText("")
        self.label_R_C.setObjectName("label_R_C")
        self.label_R_R2 = QtWidgets.QLabel(self.frame)
        self.label_R_R2.setGeometry(QtCore.QRect(90, 310, 101, 16))
        self.label_R_R2.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_R_R2.setText("")
        self.label_R_R2.setObjectName("label_R_R2")
        self.label_R_Axis = QtWidgets.QLabel(self.frame)
        self.label_R_Axis.setGeometry(QtCore.QRect(90, 350, 111, 21))
        self.label_R_Axis.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_R_Axis.setText("")
        self.label_R_Axis.setObjectName("label_R_Axis")
        self.label_R_R1 = QtWidgets.QLabel(self.frame)
        self.label_R_R1.setGeometry(QtCore.QRect(90, 270, 101, 20))
        self.label_R_R1.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 14pt \"黑体\";\n"
"color: rgb(255, 255, 0);")
        self.label_R_R1.setText("")
        self.label_R_R1.setObjectName("label_R_R1")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 83, 540))
        self.graphicsView.setStyleSheet("background-image: url(:/toppage/icon/toppage/BG-left.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 130, 15, 20))
        self.label.setStyleSheet("background-image: url(:/toppage/icon/toppage/S.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 15, 20))
        self.label_2.setStyleSheet("background-image: url(:/toppage/icon/toppage/C.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 230, 15, 20))
        self.label_3.setStyleSheet("background-image: url(:/toppage/icon/toppage/A.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView_2.setGeometry(QtCore.QRect(720, 0, 80, 540))
        self.graphicsView_2.setStyleSheet("background-image: url(:/toppage/icon/toppage/BG-right.png);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView_3.setGeometry(QtCore.QRect(0, 539, 800, 62))
        self.graphicsView_3.setStyleSheet("background-image: url(:/toppage/icon/toppage/BG-down.png);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView_4.setGeometry(QtCore.QRect(80, 0, 642, 60))
        self.graphicsView_4.setStyleSheet("background-image: url(:/toppage/icon/toppage/BG-up.png);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.pushButton_L = QtWidgets.QPushButton(self.frame)
        self.pushButton_L.setGeometry(QtCore.QRect(730, 10, 58, 64))
        self.pushButton_L.setStyleSheet("background-image: url(:/toppage/icon/toppage/L.png);")
        self.pushButton_L.setText("")
        self.pushButton_L.setObjectName("pushButton_L")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(750, 130, 15, 20))
        self.label_4.setStyleSheet("background-image: url(:/toppage/icon/toppage/S.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(750, 180, 15, 20))
        self.label_5.setStyleSheet("background-image: url(:/toppage/icon/toppage/C.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(750, 230, 15, 20))
        self.label_6.setStyleSheet("background-image: url(:/toppage/icon/toppage/A.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_care_up = QtWidgets.QPushButton(self.frame)
        self.pushButton_care_up.setGeometry(QtCore.QRect(10, 320, 58, 64))
        self.pushButton_care_up.setStyleSheet("background-image: url(:/toppage/icon/toppage/arrow_up.png);")
        self.pushButton_care_up.setText("")
        self.pushButton_care_up.setObjectName("pushButton_care_up")
        self.pushButton_care_down = QtWidgets.QPushButton(self.frame)
        self.pushButton_care_down.setGeometry(QtCore.QRect(10, 470, 58, 64))
        self.pushButton_care_down.setStyleSheet("background-image: url(:/toppage/icon/toppage/arrow_down.png);")
        self.pushButton_care_down.setText("")
        self.pushButton_care_down.setObjectName("pushButton_care_down")
        self.pushButton_forward = QtWidgets.QPushButton(self.frame)
        self.pushButton_forward.setGeometry(QtCore.QRect(730, 320, 58, 64))
        self.pushButton_forward.setStyleSheet("background-image: url(:/toppage/icon/toppage/5.png);")
        self.pushButton_forward.setText("")
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.pushButton_backward = QtWidgets.QPushButton(self.frame)
        self.pushButton_backward.setGeometry(QtCore.QRect(730, 470, 58, 64))
        self.pushButton_backward.setStyleSheet("background-image: url(:/toppage/icon/toppage/2.png);")
        self.pushButton_backward.setText("")
        self.pushButton_backward.setObjectName("pushButton_backward")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(18, 403, 46, 50))
        self.label_7.setStyleSheet("background-image: url(:/toppage/icon/toppage/6.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(737, 410, 46, 36))
        self.label_8.setStyleSheet("background-image: url(:/toppage/icon/toppage/qianhou.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.comboBox_MODE_result = QtWidgets.QComboBox(self.frame)
        self.comboBox_MODE_result.setGeometry(QtCore.QRect(214, 545, 103, 52))
        self.comboBox_MODE_result.setStyleSheet("")
        self.comboBox_MODE_result.setCurrentText("")
        self.comboBox_MODE_result.setMaxVisibleItems(10)
        self.comboBox_MODE_result.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_MODE_result.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_MODE_result.setIconSize(QtCore.QSize(70, 50))
        self.comboBox_MODE_result.setDuplicatesEnabled(False)
        self.comboBox_MODE_result.setFrame(False)
        self.comboBox_MODE_result.setObjectName("comboBox_MODE_result")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/toppage/icon/toppage/down/ref.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/toppage/icon/toppage/down-press/ref.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/toppage/icon/toppage/down-press/ref.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox_MODE_result.addItem(icon6, "")
        self.comboBox_MODE_result.setItemText(0, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/toppage/icon/toppage/down/ker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/toppage/icon/toppage/down-press/ker.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/toppage/icon/toppage/down-press/ker.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox_MODE_result.addItem(icon7, "")
        self.comboBox_MODE_result.setItemText(1, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/toppage/icon/toppage/down/K&R.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/toppage/icon/toppage/down-press/K&R.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/toppage/icon/toppage/down-press/K&R.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox_MODE_result.addItem(icon8, "")
        self.comboBox_MODE_result.setItemText(2, "")
        self.pushButton_guiwei = QtWidgets.QPushButton(self.frame)
        self.pushButton_guiwei.setGeometry(QtCore.QRect(7, 544, 74, 54))
        self.pushButton_guiwei.setStyleSheet("background-image: url(:/toppage/icon/toppage/down/4.png);")
        self.pushButton_guiwei.setText("")
        self.pushButton_guiwei.setObjectName("pushButton_guiwei")
        self.pushButton_testkey = QtWidgets.QPushButton(self.frame)
        self.pushButton_testkey.setGeometry(QtCore.QRect(316, 544, 74, 54))
        self.pushButton_testkey.setStyleSheet("background-image: url(:/toppage/icon/toppage/down/1.png);\n"
"")
        self.pushButton_testkey.setText("")
        self.pushButton_testkey.setObjectName("pushButton_testkey")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(90, 500, 29, 31))
        self.label_9.setStyleSheet("background-image: url(:/toppage/icon/toppage/num.png);\n"
"background-color: rgba(85, 170, 255, 0);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(525, 8, 104, 44))
        self.pushButton_9.setStyleSheet("background-image: url(:/toppage/icon/shouye_top/pd.png);")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(160, 8, 127, 46))
        self.comboBox.setIconSize(QtCore.QSize(100, 40))
        self.comboBox.setObjectName("comboBox")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.25.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.25.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.25.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox.addItem(icon9, "")
        self.comboBox.setItemText(0, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.12.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.12.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox.addItem(icon10, "")
        self.comboBox.setItemText(1, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.06.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.06.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.06.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox.addItem(icon11, "")
        self.comboBox.setItemText(2, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.01.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(":/toppage/icon/shouye_top/.01.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox.addItem(icon12, "")
        self.comboBox.setItemText(3, "")
        self.widget_show_hateman = QtWidgets.QWidget(self.frame)
        self.widget_show_hateman.setGeometry(QtCore.QRect(100, 110, 602, 285))
        self.widget_show_hateman.setObjectName("widget_show_hateman")
        self.pushButtun_close_hateman = QtWidgets.QPushButton(self.widget_show_hateman)
        self.pushButtun_close_hateman.setGeometry(QtCore.QRect(557, 11, 32, 32))
        self.pushButtun_close_hateman.setStyleSheet("background-image: url(:/toppage/icon/hartmanngram/close.png);")
        self.pushButtun_close_hateman.setText("")
        self.pushButtun_close_hateman.setObjectName("pushButtun_close_hateman")
        self.label_showhateman_all = QtWidgets.QLabel(self.widget_show_hateman)
        self.label_showhateman_all.setGeometry(QtCore.QRect(0, 0, 599, 280))
        self.label_showhateman_all.setStyleSheet("background-image: url(:/toppage/icon/hartmanngram/BG.png);")
        self.label_showhateman_all.setText("")
        self.label_showhateman_all.setObjectName("label_showhateman_all")
        self.label_showhateman_r = QtWidgets.QLabel(self.widget_show_hateman)
        self.label_showhateman_r.setGeometry(QtCore.QRect(0, 50, 299, 231))
        self.label_showhateman_r.setObjectName("label_showhateman_r")
        self.label_showhateman_l = QtWidgets.QLabel(self.widget_show_hateman)
        self.label_showhateman_l.setGeometry(QtCore.QRect(300, 50, 299, 231))
        self.label_showhateman_l.setObjectName("label_showhateman_l")
        self.label_36 = QtWidgets.QLabel(self.widget_show_hateman)
        self.label_36.setGeometry(QtCore.QRect(10, 50, 54, 21))
        self.label_36.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"HGF5_CNKI\";")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.widget_show_hateman)
        self.label_37.setGeometry(QtCore.QRect(310, 50, 54, 21))
        self.label_37.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"HGF5_CNKI\";")
        self.label_37.setObjectName("label_37")
        self.label_showhateman_all.raise_()
        self.label_showhateman_l.raise_()
        self.label_showhateman_r.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.pushButtun_close_hateman.raise_()
        self.widget_show_history = QtWidgets.QWidget(self.frame)
        self.widget_show_history.setGeometry(QtCore.QRect(100, 200, 591, 261))
        self.widget_show_history.setStyleSheet("background-color: rgba(255, 170, 127, 0);")
        self.widget_show_history.setObjectName("widget_show_history")
        self.pushButton_close_history = QtWidgets.QPushButton(self.widget_show_history)
        self.pushButton_close_history.setGeometry(QtCore.QRect(430, 230, 75, 23))
        self.pushButton_close_history.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.pushButton_close_history.setObjectName("pushButton_close_history")
        self.tableWidget_history_l_ref = QtWidgets.QTableWidget(self.widget_show_history)
        self.tableWidget_history_l_ref.setGeometry(QtCore.QRect(300, 0, 302, 211))
        self.tableWidget_history_l_ref.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.tableWidget_history_l_ref.setRowCount(6)
        self.tableWidget_history_l_ref.setColumnCount(3)
        self.tableWidget_history_l_ref.setObjectName("tableWidget_history_l_ref")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_l_ref.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_l_ref.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_l_ref.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_l_ref.setItem(0, 0, item)
        self.tableWidget_history_l_ref.horizontalHeader().setVisible(False)
        self.tableWidget_history_l_ref.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_history_l_ref.horizontalHeader().setHighlightSections(False)
        self.tableWidget_history_l_ref.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_history_l_ref.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_history_l_ref.verticalHeader().setVisible(False)
        self.pushButton_clear_history = QtWidgets.QPushButton(self.widget_show_history)
        self.pushButton_clear_history.setGeometry(QtCore.QRect(90, 230, 75, 23))
        self.pushButton_clear_history.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.pushButton_clear_history.setObjectName("pushButton_clear_history")
        self.tableWidget_history_r_ref = QtWidgets.QTableWidget(self.widget_show_history)
        self.tableWidget_history_r_ref.setGeometry(QtCore.QRect(0, 0, 302, 211))
        self.tableWidget_history_r_ref.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.tableWidget_history_r_ref.setShowGrid(True)
        self.tableWidget_history_r_ref.setRowCount(6)
        self.tableWidget_history_r_ref.setColumnCount(3)
        self.tableWidget_history_r_ref.setObjectName("tableWidget_history_r_ref")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_r_ref.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_r_ref.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_r_ref.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_r_ref.setHorizontalHeaderItem(2, item)
        self.tableWidget_history_r_ref.horizontalHeader().setVisible(False)
        self.tableWidget_history_r_ref.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_history_r_ref.horizontalHeader().setHighlightSections(False)
        self.tableWidget_history_r_ref.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_history_r_ref.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_history_r_ref.verticalHeader().setVisible(False)
        self.tableWidget_history_r_ker = QtWidgets.QTableWidget(self.widget_show_history)
        self.tableWidget_history_r_ker.setGeometry(QtCore.QRect(0, 0, 302, 211))
        self.tableWidget_history_r_ker.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.tableWidget_history_r_ker.setShowGrid(True)
        self.tableWidget_history_r_ker.setRowCount(6)
        self.tableWidget_history_r_ker.setColumnCount(3)
        self.tableWidget_history_r_ker.setObjectName("tableWidget_history_r_ker")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_r_ker.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_r_ker.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_r_ker.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_r_ker.setHorizontalHeaderItem(2, item)
        self.tableWidget_history_r_ker.horizontalHeader().setVisible(False)
        self.tableWidget_history_r_ker.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_history_r_ker.horizontalHeader().setHighlightSections(False)
        self.tableWidget_history_r_ker.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_history_r_ker.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_history_r_ker.verticalHeader().setVisible(False)
        self.tableWidget_history_l_ker = QtWidgets.QTableWidget(self.widget_show_history)
        self.tableWidget_history_l_ker.setGeometry(QtCore.QRect(300, 0, 302, 211))
        self.tableWidget_history_l_ker.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.tableWidget_history_l_ker.setRowCount(6)
        self.tableWidget_history_l_ker.setColumnCount(3)
        self.tableWidget_history_l_ker.setObjectName("tableWidget_history_l_ker")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_l_ker.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_l_ker.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_l_ker.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history_l_ker.setItem(0, 0, item)
        self.tableWidget_history_l_ker.horizontalHeader().setVisible(False)
        self.tableWidget_history_l_ker.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_history_l_ker.horizontalHeader().setHighlightSections(False)
        self.tableWidget_history_l_ker.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_history_l_ker.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_history_l_ker.verticalHeader().setVisible(False)
        self.pushButton_history_show_ker = QtWidgets.QPushButton(self.widget_show_history)
        self.pushButton_history_show_ker.setGeometry(QtCore.QRect(210, 230, 75, 23))
        self.pushButton_history_show_ker.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.pushButton_history_show_ker.setObjectName("pushButton_history_show_ker")
        self.pushButton_history_show_ref = QtWidgets.QPushButton(self.widget_show_history)
        self.pushButton_history_show_ref.setGeometry(QtCore.QRect(320, 230, 75, 23))
        self.pushButton_history_show_ref.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.pushButton_history_show_ref.setObjectName("pushButton_history_show_ref")
        self.pushButton_close_history.raise_()
        self.pushButton_clear_history.raise_()
        self.tableWidget_history_r_ker.raise_()
        self.tableWidget_history_l_ker.raise_()
        self.pushButton_history_show_ker.raise_()
        self.pushButton_history_show_ref.raise_()
        self.tableWidget_history_l_ref.raise_()
        self.tableWidget_history_r_ref.raise_()
        self.label_show_finished = QtWidgets.QLabel(self.frame)
        self.label_show_finished.setGeometry(QtCore.QRect(350, 470, 131, 21))
        self.label_show_finished.setStyleSheet("color: rgb(85, 255, 127);\n"
"font: 75 14pt \"仿宋\";\n"
"background-color: rgba(85, 255, 0, 0);")
        self.label_show_finished.setObjectName("label_show_finished")
        self.label_show_temperture = QtWidgets.QLabel(self.frame)
        self.label_show_temperture.setGeometry(QtCore.QRect(640, 500, 61, 21))
        self.label_show_temperture.setStyleSheet("background-color: rgba(129, 120, 255, 0);")
        self.label_show_temperture.setText("")
        self.label_show_temperture.setObjectName("label_show_temperture")
        self.label_show_num_test = QtWidgets.QLabel(self.frame)
        self.label_show_num_test.setGeometry(QtCore.QRect(130, 510, 61, 21))
        self.label_show_num_test.setStyleSheet("background-color: rgba(129, 120, 255, 0);")
        self.label_show_num_test.setText("")
        self.label_show_num_test.setObjectName("label_show_num_test")
        self.label_PD = QtWidgets.QLabel(self.frame)
        self.label_PD.setGeometry(QtCore.QRect(570, 20, 61, 21))
        self.label_PD.setStyleSheet("background-color: rgba(85, 85, 255, 0);\n"
"font: 16pt \"黑体\";\n"
"color: rgb(255, 255, 255);")
        self.label_PD.setText("")
        self.label_PD.setObjectName("label_PD")
        self.graphicsView_3.raise_()
        self.graphicsView_2.raise_()
        self.pushButton_show_hateman.raise_()
        self.graphicsView.raise_()
        self.graphicsView_4.raise_()
        self.pushButton_clear.raise_()
        self.pushButton_set.raise_()
        self.pushButton_4.raise_()
        self.pushButton_R.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton_L.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.pushButton_care_up.raise_()
        self.pushButton_care_down.raise_()
        self.pushButton_forward.raise_()
        self.pushButton_backward.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.pushButton_HIS.raise_()
        self.pushButton_guiwei.raise_()
        self.label_show_pic.raise_()
        self.label_L_A.raise_()
        self.label_R_S.raise_()
        self.label_L_S.raise_()
        self.label_R_A.raise_()
        self.label_R_C.raise_()
        self.label_L_C.raise_()
        self.comboBox_MODE_result.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.comboBox_3.raise_()
        self.pushButton_9.raise_()
        self.label_L_Axis.raise_()
        self.label_L_R1.raise_()
        self.label_L_R2.raise_()
        self.label_R_R1.raise_()
        self.label_R_R2.raise_()
        self.label_R_Axis.raise_()
        self.pushButton_testkey.raise_()
        self.label_9.raise_()
        self.label_show_finished.raise_()
        self.widget_show_hateman.raise_()
        self.label_show_temperture.raise_()
        self.label_show_num_test.raise_()
        self.widget_show_history.raise_()
        self.label_PD.raise_()
        self.yanguangyi.addWidget(self.page_main_win)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 70, 680, 480))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_quguangdu = QtWidgets.QWidget()
        self.page_quguangdu.setObjectName("page_quguangdu")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_3.setGeometry(QtCore.QRect(240, 70, 81, 21))
        self.checkBox_3.setAcceptDrops(True)
        self.checkBox_3.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_5 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_5.setGeometry(QtCore.QRect(320, 240, 81, 21))
        self.checkBox_5.setAcceptDrops(True)
        self.checkBox_5.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_10 = QtWidgets.QLabel(self.page_quguangdu)
        self.label_10.setGeometry(QtCore.QRect(60, 200, 51, 20))
        self.label_10.setStyleSheet("font: 14pt \"黑体\";")
        self.label_10.setObjectName("label_10")
        self.checkBox_8 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_8.setGeometry(QtCore.QRect(70, 160, 81, 21))
        self.checkBox_8.setAcceptDrops(True)
        self.checkBox_8.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_9.setGeometry(QtCore.QRect(160, 240, 81, 21))
        self.checkBox_9.setAcceptDrops(True)
        self.checkBox_9.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_4 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_4.setGeometry(QtCore.QRect(320, 70, 81, 21))
        self.checkBox_4.setAcceptDrops(True)
        self.checkBox_4.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_11 = QtWidgets.QLabel(self.page_quguangdu)
        self.label_11.setGeometry(QtCore.QRect(60, 120, 61, 21))
        self.label_11.setStyleSheet("font: 14pt \"黑体\";")
        self.label_11.setObjectName("label_11")
        self.checkBox_15 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_15.setGeometry(QtCore.QRect(70, 350, 81, 21))
        self.checkBox_15.setAcceptDrops(True)
        self.checkBox_15.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_15.setObjectName("checkBox_15")
        self.label_12 = QtWidgets.QLabel(self.page_quguangdu)
        self.label_12.setGeometry(QtCore.QRect(60, 292, 51, 20))
        self.label_12.setStyleSheet("font: 14pt \"黑体\";")
        self.label_12.setObjectName("label_12")
        self.checkBox_10 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_10.setGeometry(QtCore.QRect(240, 240, 81, 21))
        self.checkBox_10.setAcceptDrops(True)
        self.checkBox_10.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_11.setGeometry(QtCore.QRect(70, 240, 81, 21))
        self.checkBox_11.setAcceptDrops(True)
        self.checkBox_11.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_2.setGeometry(QtCore.QRect(160, 70, 81, 21))
        self.checkBox_2.setAcceptDrops(True)
        self.checkBox_2.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_13 = QtWidgets.QLabel(self.page_quguangdu)
        self.label_13.setGeometry(QtCore.QRect(60, 40, 54, 12))
        self.label_13.setStyleSheet("font: 14pt \"黑体\";")
        self.label_13.setObjectName("label_13")
        self.checkBox_16 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_16.setGeometry(QtCore.QRect(160, 350, 81, 21))
        self.checkBox_16.setAcceptDrops(True)
        self.checkBox_16.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_7 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_7.setGeometry(QtCore.QRect(240, 160, 81, 21))
        self.checkBox_7.setAcceptDrops(True)
        self.checkBox_7.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox.setGeometry(QtCore.QRect(70, 70, 81, 21))
        self.checkBox.setAcceptDrops(True)
        self.checkBox.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_6 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_6.setGeometry(QtCore.QRect(160, 160, 81, 21))
        self.checkBox_6.setAcceptDrops(True)
        self.checkBox_6.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_6.setObjectName("checkBox_6")
        self.stackedWidget.addWidget(self.page_quguangdu)
        self.page_qulv = QtWidgets.QWidget()
        self.page_qulv.setObjectName("page_qulv")
        self.checkBox_19 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_19.setGeometry(QtCore.QRect(240, 350, 81, 21))
        self.checkBox_19.setAcceptDrops(True)
        self.checkBox_19.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_23 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_23.setGeometry(QtCore.QRect(70, 170, 81, 21))
        self.checkBox_23.setAcceptDrops(True)
        self.checkBox_23.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_23.setObjectName("checkBox_23")
        self.label_14 = QtWidgets.QLabel(self.page_qulv)
        self.label_14.setGeometry(QtCore.QRect(60, 41, 41, 21))
        self.label_14.setStyleSheet("font: 14pt \"黑体\";")
        self.label_14.setObjectName("label_14")
        self.checkBox_12 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_12.setGeometry(QtCore.QRect(160, 170, 81, 21))
        self.checkBox_12.setAcceptDrops(True)
        self.checkBox_12.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_26 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_26.setGeometry(QtCore.QRect(240, 170, 81, 21))
        self.checkBox_26.setAcceptDrops(True)
        self.checkBox_26.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_18 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_18.setGeometry(QtCore.QRect(240, 80, 81, 21))
        self.checkBox_18.setAcceptDrops(True)
        self.checkBox_18.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_21 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_21.setGeometry(QtCore.QRect(70, 80, 81, 21))
        self.checkBox_21.setAcceptDrops(True)
        self.checkBox_21.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_21.setObjectName("checkBox_21")
        self.label_15 = QtWidgets.QLabel(self.page_qulv)
        self.label_15.setGeometry(QtCore.QRect(60, 302, 81, 20))
        self.label_15.setStyleSheet("font: 14pt \"黑体\";")
        self.label_15.setObjectName("label_15")
        self.checkBox_14 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_14.setGeometry(QtCore.QRect(70, 250, 81, 21))
        self.checkBox_14.setAcceptDrops(True)
        self.checkBox_14.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_17 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_17.setGeometry(QtCore.QRect(160, 350, 81, 21))
        self.checkBox_17.setAcceptDrops(True)
        self.checkBox_17.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_17.setObjectName("checkBox_17")
        self.label_16 = QtWidgets.QLabel(self.page_qulv)
        self.label_16.setGeometry(QtCore.QRect(60, 210, 61, 20))
        self.label_16.setStyleSheet("font: 14pt \"黑体\";")
        self.label_16.setObjectName("label_16")
        self.checkBox_22 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_22.setGeometry(QtCore.QRect(240, 250, 81, 21))
        self.checkBox_22.setAcceptDrops(True)
        self.checkBox_22.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_22.setObjectName("checkBox_22")
        self.label_17 = QtWidgets.QLabel(self.page_qulv)
        self.label_17.setGeometry(QtCore.QRect(60, 130, 61, 21))
        self.label_17.setStyleSheet("font: 14pt \"黑体\";")
        self.label_17.setObjectName("label_17")
        self.checkBox_24 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_24.setGeometry(QtCore.QRect(160, 250, 81, 21))
        self.checkBox_24.setAcceptDrops(True)
        self.checkBox_24.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_20 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_20.setGeometry(QtCore.QRect(70, 350, 81, 21))
        self.checkBox_20.setAcceptDrops(True)
        self.checkBox_20.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_13 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_13.setGeometry(QtCore.QRect(160, 80, 81, 21))
        self.checkBox_13.setAcceptDrops(True)
        self.checkBox_13.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_13.setObjectName("checkBox_13")
        self.stackedWidget.addWidget(self.page_qulv)
        self.page_moshi = QtWidgets.QWidget()
        self.page_moshi.setObjectName("page_moshi")
        self.checkBox_39 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_39.setGeometry(QtCore.QRect(280, 290, 81, 21))
        self.checkBox_39.setAcceptDrops(True)
        self.checkBox_39.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_39.setObjectName("checkBox_39")
        self.label_18 = QtWidgets.QLabel(self.page_moshi)
        self.label_18.setGeometry(QtCore.QRect(30, 100, 61, 21))
        self.label_18.setStyleSheet("font: 14pt \"黑体\";")
        self.label_18.setObjectName("label_18")
        self.checkBox_29 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_29.setGeometry(QtCore.QRect(40, 209, 81, 21))
        self.checkBox_29.setAcceptDrops(True)
        self.checkBox_29.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_29.setObjectName("checkBox_29")
        self.label_19 = QtWidgets.QLabel(self.page_moshi)
        self.label_19.setGeometry(QtCore.QRect(30, 261, 81, 20))
        self.label_19.setStyleSheet("font: 14pt \"黑体\";")
        self.label_19.setObjectName("label_19")
        self.checkBox_37 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_37.setGeometry(QtCore.QRect(210, 290, 61, 21))
        self.checkBox_37.setAcceptDrops(True)
        self.checkBox_37.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_38.setGeometry(QtCore.QRect(280, 130, 81, 21))
        self.checkBox_38.setAcceptDrops(True)
        self.checkBox_38.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_31 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_31.setGeometry(QtCore.QRect(40, 290, 81, 21))
        self.checkBox_31.setAcceptDrops(True)
        self.checkBox_31.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_27 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_27.setGeometry(QtCore.QRect(130, 130, 81, 21))
        self.checkBox_27.setAcceptDrops(True)
        self.checkBox_27.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_27.setObjectName("checkBox_27")
        self.spinBox = QtWidgets.QSpinBox(self.page_moshi)
        self.spinBox.setGeometry(QtCore.QRect(390, 370, 42, 22))
        self.spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox.setObjectName("spinBox")
        self.checkBox_35 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_35.setGeometry(QtCore.QRect(130, 209, 81, 21))
        self.checkBox_35.setAcceptDrops(True)
        self.checkBox_35.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_single_eye = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_single_eye.setGeometry(QtCore.QRect(40, 60, 81, 21))
        self.checkBox_single_eye.setAcceptDrops(True)
        self.checkBox_single_eye.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_single_eye.setChecked(True)
        self.checkBox_single_eye.setObjectName("checkBox_single_eye")
        self.label_20 = QtWidgets.QLabel(self.page_moshi)
        self.label_20.setGeometry(QtCore.QRect(30, 340, 81, 20))
        self.label_20.setStyleSheet("font: 14pt \"黑体\";")
        self.label_20.setObjectName("label_20")
        self.horizontalSlider = QtWidgets.QSlider(self.page_moshi)
        self.horizontalSlider.setGeometry(QtCore.QRect(130, 370, 221, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_21 = QtWidgets.QLabel(self.page_moshi)
        self.label_21.setGeometry(QtCore.QRect(30, 180, 61, 20))
        self.label_21.setStyleSheet("font: 14pt \"黑体\";")
        self.label_21.setObjectName("label_21")
        self.checkBox_25 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_25.setGeometry(QtCore.QRect(130, 290, 81, 21))
        self.checkBox_25.setAcceptDrops(True)
        self.checkBox_25.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_25.setObjectName("checkBox_25")
        self.label_22 = QtWidgets.QLabel(self.page_moshi)
        self.label_22.setGeometry(QtCore.QRect(40, 370, 81, 20))
        self.label_22.setStyleSheet("font: 14pt \"黑体\";")
        self.label_22.setObjectName("label_22")
        self.checkBox_36 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_36.setGeometry(QtCore.QRect(210, 130, 51, 21))
        self.checkBox_36.setAcceptDrops(True)
        self.checkBox_36.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_36.setObjectName("checkBox_36")
        self.label_23 = QtWidgets.QLabel(self.page_moshi)
        self.label_23.setGeometry(QtCore.QRect(30, 30, 41, 21))
        self.label_23.setStyleSheet("font: 14pt \"黑体\";")
        self.label_23.setObjectName("label_23")
        self.checkBox_34 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_34.setGeometry(QtCore.QRect(40, 130, 81, 21))
        self.checkBox_34.setAcceptDrops(True)
        self.checkBox_34.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_33 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_33.setGeometry(QtCore.QRect(210, 209, 51, 21))
        self.checkBox_33.setAcceptDrops(True)
        self.checkBox_33.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_33.setObjectName("checkBox_33")
        self.stackedWidget.addWidget(self.page_moshi)
        self.page_printset = QtWidgets.QWidget()
        self.page_printset.setObjectName("page_printset")
        self.checkBox_52 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_52.setGeometry(QtCore.QRect(270, 40, 81, 21))
        self.checkBox_52.setAcceptDrops(True)
        self.checkBox_52.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_52.setObjectName("checkBox_52")
        self.label_24 = QtWidgets.QLabel(self.page_printset)
        self.label_24.setGeometry(QtCore.QRect(30, 80, 61, 21))
        self.label_24.setStyleSheet("font: 14pt \"黑体\";")
        self.label_24.setObjectName("label_24")
        self.checkBox_30 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_30.setGeometry(QtCore.QRect(100, 250, 61, 21))
        self.checkBox_30.setAcceptDrops(True)
        self.checkBox_30.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_30.setObjectName("checkBox_30")
        self.label_25 = QtWidgets.QLabel(self.page_printset)
        self.label_25.setGeometry(QtCore.QRect(30, 10, 81, 21))
        self.label_25.setStyleSheet("font: 14pt \"黑体\";")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.page_printset)
        self.label_26.setGeometry(QtCore.QRect(30, 222, 81, 20))
        self.label_26.setStyleSheet("font: 14pt \"黑体\";")
        self.label_26.setObjectName("label_26")
        self.checkBox_48 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_48.setGeometry(QtCore.QRect(210, 110, 81, 21))
        self.checkBox_48.setAcceptDrops(True)
        self.checkBox_48.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_48.setObjectName("checkBox_48")
        self.label_27 = QtWidgets.QLabel(self.page_printset)
        self.label_27.setGeometry(QtCore.QRect(30, 282, 81, 20))
        self.label_27.setStyleSheet("font: 14pt \"黑体\";")
        self.label_27.setObjectName("label_27")
        self.checkBox_41 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_41.setGeometry(QtCore.QRect(130, 40, 81, 21))
        self.checkBox_41.setAcceptDrops(True)
        self.checkBox_41.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_54 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_54.setGeometry(QtCore.QRect(230, 310, 61, 21))
        self.checkBox_54.setAcceptDrops(True)
        self.checkBox_54.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_54.setObjectName("checkBox_54")
        self.label_28 = QtWidgets.QLabel(self.page_printset)
        self.label_28.setGeometry(QtCore.QRect(210, 340, 81, 20))
        self.label_28.setStyleSheet("font: 14pt \"黑体\";")
        self.label_28.setObjectName("label_28")
        self.checkBox_47 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_47.setGeometry(QtCore.QRect(40, 180, 61, 21))
        self.checkBox_47.setAcceptDrops(True)
        self.checkBox_47.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_47.setObjectName("checkBox_47")
        self.checkBox_55 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_55.setGeometry(QtCore.QRect(290, 310, 81, 21))
        self.checkBox_55.setAcceptDrops(True)
        self.checkBox_55.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_55.setObjectName("checkBox_55")
        self.checkBox_60 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_60.setGeometry(QtCore.QRect(40, 370, 61, 21))
        self.checkBox_60.setAcceptDrops(True)
        self.checkBox_60.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_60.setObjectName("checkBox_60")
        self.checkBox_40 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_40.setGeometry(QtCore.QRect(130, 110, 81, 21))
        self.checkBox_40.setAcceptDrops(True)
        self.checkBox_40.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_46 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_46.setGeometry(QtCore.QRect(40, 110, 61, 21))
        self.checkBox_46.setAcceptDrops(True)
        self.checkBox_46.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_46.setObjectName("checkBox_46")
        self.checkBox_58 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_58.setGeometry(QtCore.QRect(290, 370, 81, 21))
        self.checkBox_58.setAcceptDrops(True)
        self.checkBox_58.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_58.setObjectName("checkBox_58")
        self.label_29 = QtWidgets.QLabel(self.page_printset)
        self.label_29.setGeometry(QtCore.QRect(210, 220, 81, 20))
        self.label_29.setStyleSheet("font: 14pt \"黑体\";")
        self.label_29.setObjectName("label_29")
        self.checkBox_42 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_42.setGeometry(QtCore.QRect(130, 180, 81, 21))
        self.checkBox_42.setAcceptDrops(True)
        self.checkBox_42.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_44 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_44.setGeometry(QtCore.QRect(40, 40, 81, 21))
        self.checkBox_44.setAcceptDrops(True)
        self.checkBox_44.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_50 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_50.setGeometry(QtCore.QRect(210, 180, 81, 21))
        self.checkBox_50.setAcceptDrops(True)
        self.checkBox_50.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_50.setObjectName("checkBox_50")
        self.checkBox_56 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_56.setGeometry(QtCore.QRect(40, 310, 61, 21))
        self.checkBox_56.setAcceptDrops(True)
        self.checkBox_56.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_56.setObjectName("checkBox_56")
        self.checkBox_43 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_43.setGeometry(QtCore.QRect(40, 250, 61, 21))
        self.checkBox_43.setAcceptDrops(True)
        self.checkBox_43.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_53 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_53.setGeometry(QtCore.QRect(200, 40, 51, 21))
        self.checkBox_53.setAcceptDrops(True)
        self.checkBox_53.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_53.setObjectName("checkBox_53")
        self.label_30 = QtWidgets.QLabel(self.page_printset)
        self.label_30.setGeometry(QtCore.QRect(210, 280, 81, 20))
        self.label_30.setStyleSheet("font: 14pt \"黑体\";")
        self.label_30.setObjectName("label_30")
        self.checkBox_49 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_49.setGeometry(QtCore.QRect(230, 250, 61, 21))
        self.checkBox_49.setAcceptDrops(True)
        self.checkBox_49.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_49.setObjectName("checkBox_49")
        self.checkBox_51 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_51.setGeometry(QtCore.QRect(290, 250, 81, 21))
        self.checkBox_51.setAcceptDrops(True)
        self.checkBox_51.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_51.setObjectName("checkBox_51")
        self.checkBox_59 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_59.setGeometry(QtCore.QRect(100, 370, 61, 21))
        self.checkBox_59.setAcceptDrops(True)
        self.checkBox_59.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_59.setObjectName("checkBox_59")
        self.label_31 = QtWidgets.QLabel(self.page_printset)
        self.label_31.setGeometry(QtCore.QRect(30, 342, 81, 20))
        self.label_31.setStyleSheet("font: 14pt \"黑体\";")
        self.label_31.setObjectName("label_31")
        self.checkBox_45 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_45.setGeometry(QtCore.QRect(100, 310, 61, 21))
        self.checkBox_45.setAcceptDrops(True)
        self.checkBox_45.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_45.setObjectName("checkBox_45")
        self.checkBox_57 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_57.setGeometry(QtCore.QRect(230, 370, 61, 21))
        self.checkBox_57.setAcceptDrops(True)
        self.checkBox_57.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_57.setObjectName("checkBox_57")
        self.label_32 = QtWidgets.QLabel(self.page_printset)
        self.label_32.setGeometry(QtCore.QRect(30, 150, 61, 20))
        self.label_32.setStyleSheet("font: 14pt \"黑体\";")
        self.label_32.setObjectName("label_32")
        self.stackedWidget.addWidget(self.page_printset)
        self.page_shuju = QtWidgets.QWidget()
        self.page_shuju.setObjectName("page_shuju")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.page_shuju)
        self.dateTimeEdit.setGeometry(QtCore.QRect(120, 90, 401, 51))
        self.dateTimeEdit.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(195, 195, 195);")
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 18), QtCore.QTime(12, 20, 0)))
        self.dateTimeEdit.setDate(QtCore.QDate(2021, 1, 18))
        self.dateTimeEdit.setTime(QtCore.QTime(12, 20, 0))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_33 = QtWidgets.QLabel(self.page_shuju)
        self.label_33.setGeometry(QtCore.QRect(80, 20, 151, 41))
        self.label_33.setStyleSheet("font: 14pt \"黑体\";")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.page_shuju)
        self.label_34.setGeometry(QtCore.QRect(80, 190, 151, 41))
        self.label_34.setStyleSheet("font: 14pt \"黑体\";")
        self.label_34.setObjectName("label_34")
        self.spinBox_2 = QtWidgets.QSpinBox(self.page_shuju)
        self.spinBox_2.setGeometry(QtCore.QRect(150, 240, 81, 31))
        self.spinBox_2.setStyleSheet("font: 14pt \"黑体\";")
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_35 = QtWidgets.QLabel(self.page_shuju)
        self.label_35.setGeometry(QtCore.QRect(80, 280, 151, 41))
        self.label_35.setStyleSheet("font: 14pt \"黑体\";")
        self.label_35.setObjectName("label_35")
        self.checkBox_61 = QtWidgets.QCheckBox(self.page_shuju)
        self.checkBox_61.setGeometry(QtCore.QRect(210, 330, 61, 21))
        self.checkBox_61.setAcceptDrops(True)
        self.checkBox_61.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_61.setObjectName("checkBox_61")
        self.checkBox_62 = QtWidgets.QCheckBox(self.page_shuju)
        self.checkBox_62.setGeometry(QtCore.QRect(150, 330, 61, 21))
        self.checkBox_62.setAcceptDrops(True)
        self.checkBox_62.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_62.setObjectName("checkBox_62")
        self.stackedWidget.addWidget(self.page_shuju)
        self.page_shujuku = QtWidgets.QWidget()
        self.page_shujuku.setObjectName("page_shujuku")
        self.set_pushButton_get_hostname = QtWidgets.QPushButton(self.page_shujuku)
        self.set_pushButton_get_hostname.setGeometry(QtCore.QRect(30, 110, 111, 23))
        self.set_pushButton_get_hostname.setObjectName("set_pushButton_get_hostname")
        self.label_show_hostname = QtWidgets.QLabel(self.page_shujuku)
        self.label_show_hostname.setGeometry(QtCore.QRect(170, 110, 231, 31))
        self.label_show_hostname.setText("")
        self.label_show_hostname.setObjectName("label_show_hostname")
        self.stackedWidget.addWidget(self.page_shujuku)
        self.page_devmode = QtWidgets.QWidget()
        self.page_devmode.setObjectName("page_devmode")
        self.label_dev_exit_process = QtWidgets.QLabel(self.page_devmode)
        self.label_dev_exit_process.setGeometry(QtCore.QRect(0, -10, 680, 480))
        self.label_dev_exit_process.setText("")
        self.label_dev_exit_process.setObjectName("label_dev_exit_process")
        self.dev_pushButton_test_all = QtWidgets.QPushButton(self.page_devmode)
        self.dev_pushButton_test_all.setGeometry(QtCore.QRect(10, 130, 81, 41))
        self.dev_pushButton_test_all.setStyleSheet("font: 12pt \"黑体\";\n"
"")
        self.dev_pushButton_test_all.setObjectName("dev_pushButton_test_all")
        self.dev_pushButton_test_motor = QtWidgets.QPushButton(self.page_devmode)
        self.dev_pushButton_test_motor.setGeometry(QtCore.QRect(10, 80, 81, 41))
        self.dev_pushButton_test_motor.setStyleSheet("font: 12pt \"黑体\";\n"
"\n"
"")
        self.dev_pushButton_test_motor.setObjectName("dev_pushButton_test_motor")
        self.dev_pushButton_open_hateman = QtWidgets.QPushButton(self.page_devmode)
        self.dev_pushButton_open_hateman.setGeometry(QtCore.QRect(10, 30, 81, 41))
        self.dev_pushButton_open_hateman.setStyleSheet("font: 12pt \"黑体\";\n"
"")
        self.dev_pushButton_open_hateman.setObjectName("dev_pushButton_open_hateman")
        self.dev_pushButton_save_zero = QtWidgets.QPushButton(self.page_devmode)
        self.dev_pushButton_save_zero.setGeometry(QtCore.QRect(590, 390, 75, 23))
        self.dev_pushButton_save_zero.setObjectName("dev_pushButton_save_zero")
        self.dev_pushButton_close_hateman = QtWidgets.QPushButton(self.page_devmode)
        self.dev_pushButton_close_hateman.setGeometry(QtCore.QRect(590, 430, 81, 23))
        self.dev_pushButton_close_hateman.setObjectName("dev_pushButton_close_hateman")
        self.label_38 = QtWidgets.QLabel(self.page_devmode)
        self.label_38.setGeometry(QtCore.QRect(0, 370, 71, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.page_devmode)
        self.label_39.setGeometry(QtCore.QRect(0, 420, 81, 16))
        self.label_39.setObjectName("label_39")
        self.spinBox_dev_laser = QtWidgets.QSpinBox(self.page_devmode)
        self.spinBox_dev_laser.setGeometry(QtCore.QRect(0, 390, 42, 22))
        self.spinBox_dev_laser.setObjectName("spinBox_dev_laser")
        self.spinBox_dev_yuanhuan = QtWidgets.QSpinBox(self.page_devmode)
        self.spinBox_dev_yuanhuan.setGeometry(QtCore.QRect(0, 440, 42, 22))
        self.spinBox_dev_yuanhuan.setObjectName("spinBox_dev_yuanhuan")
        self.slider_dev_laser = QtWidgets.QSlider(self.page_devmode)
        self.slider_dev_laser.setGeometry(QtCore.QRect(50, 390, 160, 22))
        self.slider_dev_laser.setOrientation(QtCore.Qt.Horizontal)
        self.slider_dev_laser.setObjectName("slider_dev_laser")
        self.slider_dev_yuanhuan = QtWidgets.QSlider(self.page_devmode)
        self.slider_dev_yuanhuan.setGeometry(QtCore.QRect(50, 440, 160, 22))
        self.slider_dev_yuanhuan.setOrientation(QtCore.Qt.Horizontal)
        self.slider_dev_yuanhuan.setObjectName("slider_dev_yuanhuan")
        self.dev_pushButton_stop_test = QtWidgets.QPushButton(self.page_devmode)
        self.dev_pushButton_stop_test.setGeometry(QtCore.QRect(10, 180, 81, 41))
        self.dev_pushButton_stop_test.setStyleSheet("font: 12pt \"黑体\";\n"
"")
        self.dev_pushButton_stop_test.setObjectName("dev_pushButton_stop_test")
        self.dev_pushButton_wuxiang_forward = QtWidgets.QPushButton(self.page_devmode)
        self.dev_pushButton_wuxiang_forward.setGeometry(QtCore.QRect(240, 372, 121, 41))
        self.dev_pushButton_wuxiang_forward.setStyleSheet("font: 12pt \"黑体\";\n"
"")
        self.dev_pushButton_wuxiang_forward.setObjectName("dev_pushButton_wuxiang_forward")
        self.dev_pushButton_wuxiang_backward = QtWidgets.QPushButton(self.page_devmode)
        self.dev_pushButton_wuxiang_backward.setGeometry(QtCore.QRect(240, 430, 121, 41))
        self.dev_pushButton_wuxiang_backward.setStyleSheet("font: 12pt \"黑体\";\n"
"")
        self.dev_pushButton_wuxiang_backward.setObjectName("dev_pushButton_wuxiang_backward")
        self.dev_pushButton_exit_sys = QtWidgets.QPushButton(self.page_devmode)
        self.dev_pushButton_exit_sys.setGeometry(QtCore.QRect(10, 230, 81, 41))
        self.dev_pushButton_exit_sys.setStyleSheet("font: 12pt \"黑体\";\n"
"")
        self.dev_pushButton_exit_sys.setObjectName("dev_pushButton_exit_sys")
        self.checkBox_show_contours = QtWidgets.QCheckBox(self.page_devmode)
        self.checkBox_show_contours.setEnabled(True)
        self.checkBox_show_contours.setGeometry(QtCore.QRect(10, 310, 101, 21))
        self.checkBox_show_contours.setAcceptDrops(True)
        self.checkBox_show_contours.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_show_contours.setChecked(False)
        self.checkBox_show_contours.setObjectName("checkBox_show_contours")
        self.stackedWidget.addWidget(self.page_devmode)
        self.set_pushButton_quguangdu = QtWidgets.QPushButton(self.page_2)
        self.set_pushButton_quguangdu.setGeometry(QtCore.QRect(90, 30, 81, 31))
        self.set_pushButton_quguangdu.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.set_pushButton_quguangdu.setObjectName("set_pushButton_quguangdu")
        self.set_pushButton_xinxi = QtWidgets.QPushButton(self.page_2)
        self.set_pushButton_xinxi.setGeometry(QtCore.QRect(540, 30, 81, 31))
        self.set_pushButton_xinxi.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.set_pushButton_xinxi.setObjectName("set_pushButton_xinxi")
        self.set_pushButton_printset = QtWidgets.QPushButton(self.page_2)
        self.set_pushButton_printset.setGeometry(QtCore.QRect(360, 30, 81, 31))
        self.set_pushButton_printset.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.set_pushButton_printset.setObjectName("set_pushButton_printset")
        self.set_pushButton_moshi = QtWidgets.QPushButton(self.page_2)
        self.set_pushButton_moshi.setGeometry(QtCore.QRect(270, 30, 81, 31))
        self.set_pushButton_moshi.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.set_pushButton_moshi.setObjectName("set_pushButton_moshi")
        self.set_pushButton_qulv = QtWidgets.QPushButton(self.page_2)
        self.set_pushButton_qulv.setGeometry(QtCore.QRect(180, 30, 81, 31))
        self.set_pushButton_qulv.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.set_pushButton_qulv.setObjectName("set_pushButton_qulv")
        self.set_pushButton_back = QtWidgets.QPushButton(self.page_2)
        self.set_pushButton_back.setGeometry(QtCore.QRect(310, 560, 81, 31))
        self.set_pushButton_back.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.set_pushButton_back.setObjectName("set_pushButton_back")
        self.set_pushButton_shuju = QtWidgets.QPushButton(self.page_2)
        self.set_pushButton_shuju.setGeometry(QtCore.QRect(450, 30, 75, 31))
        self.set_pushButton_shuju.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.set_pushButton_shuju.setObjectName("set_pushButton_shuju")
        self.set_pushButton_dev = QtWidgets.QPushButton(self.page_2)
        self.set_pushButton_dev.setGeometry(QtCore.QRect(630, 30, 81, 31))
        self.set_pushButton_dev.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.set_pushButton_dev.setObjectName("set_pushButton_dev")
        self.yanguangyi.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.yanguangyi.setCurrentIndex(0)
        self.comboBox_MODE_result.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(6)
        self.slider_dev_laser.valueChanged['int'].connect(self.spinBox_dev_laser.setValue)
        self.slider_dev_yuanhuan.valueChanged['int'].connect(self.spinBox_dev_yuanhuan.setValue)
        self.spinBox_dev_laser.valueChanged['int'].connect(self.slider_dev_laser.setValue)
        self.spinBox_dev_yuanhuan.valueChanged['int'].connect(self.slider_dev_yuanhuan.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_showhateman_r.setText(_translate("MainWindow", "TextLabel"))
        self.label_showhateman_l.setText(_translate("MainWindow", "TextLabel"))
        self.label_36.setText(_translate("MainWindow", "R"))
        self.label_37.setText(_translate("MainWindow", "L"))
        self.pushButton_close_history.setText(_translate("MainWindow", "退出"))
        item = self.tableWidget_history_l_ref.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "L-SPH"))
        item = self.tableWidget_history_l_ref.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "L-CYL"))
        item = self.tableWidget_history_l_ref.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "L-A"))
        __sortingEnabled = self.tableWidget_history_l_ref.isSortingEnabled()
        self.tableWidget_history_l_ref.setSortingEnabled(False)
        self.tableWidget_history_l_ref.setSortingEnabled(__sortingEnabled)
        self.pushButton_clear_history.setText(_translate("MainWindow", "清除"))
        item = self.tableWidget_history_r_ref.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_history_r_ref.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "R-SPH"))
        item = self.tableWidget_history_r_ref.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "R-CYL"))
        item = self.tableWidget_history_r_ref.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "R-A"))
        item = self.tableWidget_history_r_ker.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_history_r_ker.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "R-R1"))
        item = self.tableWidget_history_r_ker.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "R-R2"))
        item = self.tableWidget_history_r_ker.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "R-Axis"))
        item = self.tableWidget_history_l_ker.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "L-R1"))
        item = self.tableWidget_history_l_ker.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "L-R2"))
        item = self.tableWidget_history_l_ker.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "L-Axis"))
        __sortingEnabled = self.tableWidget_history_l_ker.isSortingEnabled()
        self.tableWidget_history_l_ker.setSortingEnabled(False)
        self.tableWidget_history_l_ker.setSortingEnabled(__sortingEnabled)
        self.pushButton_history_show_ker.setText(_translate("MainWindow", "KER"))
        self.pushButton_history_show_ref.setText(_translate("MainWindow", "REF"))
        self.label_show_finished.setText(_translate("MainWindow", "start"))
        self.checkBox_3.setText(_translate("MainWindow", "13.5"))
        self.checkBox_5.setText(_translate("MainWindow", "15.0"))
        self.label_10.setText(_translate("MainWindow", "步长"))
        self.checkBox_8.setText(_translate("MainWindow", "-"))
        self.checkBox_9.setText(_translate("MainWindow", "12.0"))
        self.checkBox_4.setText(_translate("MainWindow", "15.0"))
        self.label_11.setText(_translate("MainWindow", "柱镜"))
        self.checkBox_15.setText(_translate("MainWindow", "关闭"))
        self.label_12.setText(_translate("MainWindow", "物像"))
        self.checkBox_10.setText(_translate("MainWindow", "13.5"))
        self.checkBox_11.setText(_translate("MainWindow", "0.0"))
        self.checkBox_2.setText(_translate("MainWindow", "12.0"))
        self.label_13.setText(_translate("MainWindow", "VD"))
        self.checkBox_16.setText(_translate("MainWindow", "打开"))
        self.checkBox_7.setText(_translate("MainWindow", "+/-"))
        self.checkBox.setText(_translate("MainWindow", "0.0"))
        self.checkBox_6.setText(_translate("MainWindow", "+"))
        self.checkBox_19.setText(_translate("MainWindow", "标准"))
        self.checkBox_23.setText(_translate("MainWindow", "0.05"))
        self.label_14.setText(_translate("MainWindow", "模式"))
        self.checkBox_12.setText(_translate("MainWindow", "0.12"))
        self.checkBox_26.setText(_translate("MainWindow", "0.25"))
        self.checkBox_18.setText(_translate("MainWindow", "平均"))
        self.checkBox_21.setText(_translate("MainWindow", "半径"))
        self.label_15.setText(_translate("MainWindow", "靶标范围"))
        self.checkBox_14.setText(_translate("MainWindow", "1.332"))
        self.checkBox_17.setText(_translate("MainWindow", "接近"))
        self.label_16.setText(_translate("MainWindow", "折射率"))
        self.checkBox_22.setText(_translate("MainWindow", "1.3375"))
        self.label_17.setText(_translate("MainWindow", "步长"))
        self.checkBox_24.setText(_translate("MainWindow", "1.336"))
        self.checkBox_20.setText(_translate("MainWindow", "关闭"))
        self.checkBox_13.setText(_translate("MainWindow", "度数"))
        self.checkBox_39.setText(_translate("MainWindow", "30分"))
        self.label_18.setText(_translate("MainWindow", "蜂鸣器"))
        self.checkBox_29.setText(_translate("MainWindow", "REF"))
        self.label_19.setText(_translate("MainWindow", "待机"))
        self.checkBox_37.setText(_translate("MainWindow", "10分"))
        self.checkBox_38.setText(_translate("MainWindow", "大"))
        self.checkBox_31.setText(_translate("MainWindow", "关闭"))
        self.checkBox_27.setText(_translate("MainWindow", "小"))
        self.checkBox_35.setText(_translate("MainWindow", "KER"))
        self.checkBox_single_eye.setText(_translate("MainWindow", "单眼"))
        self.label_20.setText(_translate("MainWindow", "屏幕亮度"))
        self.label_21.setText(_translate("MainWindow", "开机"))
        self.checkBox_25.setText(_translate("MainWindow", "5分"))
        self.label_22.setText(_translate("MainWindow", "亮度："))
        self.checkBox_36.setText(_translate("MainWindow", "中"))
        self.label_23.setText(_translate("MainWindow", "测量"))
        self.checkBox_34.setText(_translate("MainWindow", "关闭"))
        self.checkBox_33.setText(_translate("MainWindow", "K R"))
        self.checkBox_52.setText(_translate("MainWindow", "100%"))
        self.label_24.setText(_translate("MainWindow", "屈光"))
        self.checkBox_30.setText(_translate("MainWindow", "打开"))
        self.label_25.setText(_translate("MainWindow", "打印浓度"))
        self.label_26.setText(_translate("MainWindow", "自动"))
        self.checkBox_48.setText(_translate("MainWindow", "平均"))
        self.label_27.setText(_translate("MainWindow", "打印清除"))
        self.checkBox_41.setText(_translate("MainWindow", "80%"))
        self.checkBox_54.setText(_translate("MainWindow", "关闭"))
        self.label_28.setText(_translate("MainWindow", "基弧"))
        self.checkBox_47.setText(_translate("MainWindow", "关闭"))
        self.checkBox_55.setText(_translate("MainWindow", "打开"))
        self.checkBox_60.setText(_translate("MainWindow", "关闭"))
        self.checkBox_40.setText(_translate("MainWindow", "标准"))
        self.checkBox_46.setText(_translate("MainWindow", "关闭"))
        self.checkBox_58.setText(_translate("MainWindow", "打开"))
        self.label_29.setText(_translate("MainWindow", "图形"))
        self.checkBox_42.setText(_translate("MainWindow", "标准"))
        self.checkBox_44.setText(_translate("MainWindow", "70%"))
        self.checkBox_50.setText(_translate("MainWindow", "平均"))
        self.checkBox_56.setText(_translate("MainWindow", "关闭"))
        self.checkBox_43.setText(_translate("MainWindow", "关闭"))
        self.checkBox_53.setText(_translate("MainWindow", "90%"))
        self.label_30.setText(_translate("MainWindow", "SE"))
        self.checkBox_49.setText(_translate("MainWindow", "关闭"))
        self.checkBox_51.setText(_translate("MainWindow", "打开"))
        self.checkBox_59.setText(_translate("MainWindow", "打开"))
        self.label_31.setText(_translate("MainWindow", "瞳孔直径"))
        self.checkBox_45.setText(_translate("MainWindow", "打开"))
        self.checkBox_57.setText(_translate("MainWindow", "关闭"))
        self.label_32.setText(_translate("MainWindow", "曲率"))
        self.label_33.setText(_translate("MainWindow", "日期/时间"))
        self.label_34.setText(_translate("MainWindow", "计数"))
        self.label_35.setText(_translate("MainWindow", "自动计数"))
        self.checkBox_61.setText(_translate("MainWindow", "打开"))
        self.checkBox_62.setText(_translate("MainWindow", "关闭"))
        self.set_pushButton_get_hostname.setText(_translate("MainWindow", "获取本机ip"))
        self.dev_pushButton_test_all.setText(_translate("MainWindow", "整机测试"))
        self.dev_pushButton_test_motor.setText(_translate("MainWindow", "电机测试"))
        self.dev_pushButton_open_hateman.setText(_translate("MainWindow", "零位校准"))
        self.dev_pushButton_save_zero.setText(_translate("MainWindow", "零位保存"))
        self.dev_pushButton_close_hateman.setText(_translate("MainWindow", "退出"))
        self.label_38.setText(_translate("MainWindow", "两点亮度"))
        self.label_39.setText(_translate("MainWindow", "圆环亮度"))
        self.dev_pushButton_stop_test.setText(_translate("MainWindow", "终止测试"))
        self.dev_pushButton_wuxiang_forward.setText(_translate("MainWindow", "物象电机向前"))
        self.dev_pushButton_wuxiang_backward.setText(_translate("MainWindow", "物象电机向后"))
        self.dev_pushButton_exit_sys.setText(_translate("MainWindow", "关闭程序"))
        self.checkBox_show_contours.setText(_translate("MainWindow", "轮廓显示"))
        self.set_pushButton_quguangdu.setText(_translate("MainWindow", "屈光度"))
        self.set_pushButton_xinxi.setText(_translate("MainWindow", "信息传送"))
        self.set_pushButton_printset.setText(_translate("MainWindow", "打印设置"))
        self.set_pushButton_moshi.setText(_translate("MainWindow", "模式"))
        self.set_pushButton_qulv.setText(_translate("MainWindow", "曲率"))
        self.set_pushButton_back.setText(_translate("MainWindow", "返回"))
        self.set_pushButton_shuju.setText(_translate("MainWindow", "数据"))
        self.set_pushButton_dev.setText(_translate("MainWindow", "开发者"))

import icons_rc
