# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        Form.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 60, 601, 421))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_quguangdu = QtWidgets.QWidget()
        self.page_quguangdu.setObjectName("page_quguangdu")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_3.setGeometry(QtCore.QRect(240, 70, 81, 21))
        self.checkBox_3.setAcceptDrops(True)
        self.checkBox_3.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_5 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_5.setGeometry(QtCore.QRect(320, 240, 81, 21))
        self.checkBox_5.setAcceptDrops(True)
        self.checkBox_5.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_3 = QtWidgets.QLabel(self.page_quguangdu)
        self.label_3.setGeometry(QtCore.QRect(60, 200, 51, 20))
        self.label_3.setStyleSheet("font: 14pt \"黑体\";")
        self.label_3.setObjectName("label_3")
        self.checkBox_8 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_8.setGeometry(QtCore.QRect(70, 160, 81, 21))
        self.checkBox_8.setAcceptDrops(True)
        self.checkBox_8.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_9.setGeometry(QtCore.QRect(160, 240, 81, 21))
        self.checkBox_9.setAcceptDrops(True)
        self.checkBox_9.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_4 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_4.setGeometry(QtCore.QRect(320, 70, 81, 21))
        self.checkBox_4.setAcceptDrops(True)
        self.checkBox_4.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_2 = QtWidgets.QLabel(self.page_quguangdu)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 61, 21))
        self.label_2.setStyleSheet("font: 14pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        self.checkBox_15 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_15.setGeometry(QtCore.QRect(70, 350, 81, 21))
        self.checkBox_15.setAcceptDrops(True)
        self.checkBox_15.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_15.setObjectName("checkBox_15")
        self.label_4 = QtWidgets.QLabel(self.page_quguangdu)
        self.label_4.setGeometry(QtCore.QRect(60, 292, 51, 20))
        self.label_4.setStyleSheet("font: 14pt \"黑体\";")
        self.label_4.setObjectName("label_4")
        self.checkBox_10 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_10.setGeometry(QtCore.QRect(240, 240, 81, 21))
        self.checkBox_10.setAcceptDrops(True)
        self.checkBox_10.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_11.setGeometry(QtCore.QRect(70, 240, 81, 21))
        self.checkBox_11.setAcceptDrops(True)
        self.checkBox_11.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_2.setGeometry(QtCore.QRect(160, 70, 81, 21))
        self.checkBox_2.setAcceptDrops(True)
        self.checkBox_2.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.label = QtWidgets.QLabel(self.page_quguangdu)
        self.label.setGeometry(QtCore.QRect(60, 40, 54, 12))
        self.label.setStyleSheet("font: 14pt \"黑体\";")
        self.label.setObjectName("label")
        self.checkBox_16 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_16.setGeometry(QtCore.QRect(160, 350, 81, 21))
        self.checkBox_16.setAcceptDrops(True)
        self.checkBox_16.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_7 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_7.setGeometry(QtCore.QRect(240, 160, 81, 21))
        self.checkBox_7.setAcceptDrops(True)
        self.checkBox_7.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox.setGeometry(QtCore.QRect(70, 70, 81, 21))
        self.checkBox.setAcceptDrops(True)
        self.checkBox.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_6 = QtWidgets.QCheckBox(self.page_quguangdu)
        self.checkBox_6.setGeometry(QtCore.QRect(160, 160, 81, 21))
        self.checkBox_6.setAcceptDrops(True)
        self.checkBox_6.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_6.setObjectName("checkBox_6")
        self.stackedWidget.addWidget(self.page_quguangdu)
        self.page_qulv = QtWidgets.QWidget()
        self.page_qulv.setObjectName("page_qulv")
        self.checkBox_19 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_19.setGeometry(QtCore.QRect(240, 350, 81, 21))
        self.checkBox_19.setAcceptDrops(True)
        self.checkBox_19.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_23 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_23.setGeometry(QtCore.QRect(70, 170, 81, 21))
        self.checkBox_23.setAcceptDrops(True)
        self.checkBox_23.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_23.setObjectName("checkBox_23")
        self.label_5 = QtWidgets.QLabel(self.page_qulv)
        self.label_5.setGeometry(QtCore.QRect(60, 41, 41, 21))
        self.label_5.setStyleSheet("font: 14pt \"黑体\";")
        self.label_5.setObjectName("label_5")
        self.checkBox_12 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_12.setGeometry(QtCore.QRect(160, 170, 81, 21))
        self.checkBox_12.setAcceptDrops(True)
        self.checkBox_12.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_26 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_26.setGeometry(QtCore.QRect(240, 170, 81, 21))
        self.checkBox_26.setAcceptDrops(True)
        self.checkBox_26.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_18 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_18.setGeometry(QtCore.QRect(240, 80, 81, 21))
        self.checkBox_18.setAcceptDrops(True)
        self.checkBox_18.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_21 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_21.setGeometry(QtCore.QRect(70, 80, 81, 21))
        self.checkBox_21.setAcceptDrops(True)
        self.checkBox_21.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_21.setObjectName("checkBox_21")
        self.label_8 = QtWidgets.QLabel(self.page_qulv)
        self.label_8.setGeometry(QtCore.QRect(60, 302, 81, 20))
        self.label_8.setStyleSheet("font: 14pt \"黑体\";")
        self.label_8.setObjectName("label_8")
        self.checkBox_14 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_14.setGeometry(QtCore.QRect(70, 250, 81, 21))
        self.checkBox_14.setAcceptDrops(True)
        self.checkBox_14.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_17 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_17.setGeometry(QtCore.QRect(160, 350, 81, 21))
        self.checkBox_17.setAcceptDrops(True)
        self.checkBox_17.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_17.setObjectName("checkBox_17")
        self.label_7 = QtWidgets.QLabel(self.page_qulv)
        self.label_7.setGeometry(QtCore.QRect(60, 210, 61, 20))
        self.label_7.setStyleSheet("font: 14pt \"黑体\";")
        self.label_7.setObjectName("label_7")
        self.checkBox_22 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_22.setGeometry(QtCore.QRect(240, 250, 81, 21))
        self.checkBox_22.setAcceptDrops(True)
        self.checkBox_22.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_22.setObjectName("checkBox_22")
        self.label_6 = QtWidgets.QLabel(self.page_qulv)
        self.label_6.setGeometry(QtCore.QRect(60, 130, 61, 21))
        self.label_6.setStyleSheet("font: 14pt \"黑体\";")
        self.label_6.setObjectName("label_6")
        self.checkBox_24 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_24.setGeometry(QtCore.QRect(160, 250, 81, 21))
        self.checkBox_24.setAcceptDrops(True)
        self.checkBox_24.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_20 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_20.setGeometry(QtCore.QRect(70, 350, 81, 21))
        self.checkBox_20.setAcceptDrops(True)
        self.checkBox_20.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_13 = QtWidgets.QCheckBox(self.page_qulv)
        self.checkBox_13.setGeometry(QtCore.QRect(160, 80, 81, 21))
        self.checkBox_13.setAcceptDrops(True)
        self.checkBox_13.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_13.setObjectName("checkBox_13")
        self.stackedWidget.addWidget(self.page_qulv)
        self.page_moshi = QtWidgets.QWidget()
        self.page_moshi.setObjectName("page_moshi")
        self.checkBox_39 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_39.setGeometry(QtCore.QRect(280, 290, 81, 21))
        self.checkBox_39.setAcceptDrops(True)
        self.checkBox_39.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_39.setObjectName("checkBox_39")
        self.label_10 = QtWidgets.QLabel(self.page_moshi)
        self.label_10.setGeometry(QtCore.QRect(30, 100, 61, 21))
        self.label_10.setStyleSheet("font: 14pt \"黑体\";")
        self.label_10.setObjectName("label_10")
        self.checkBox_29 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_29.setGeometry(QtCore.QRect(40, 209, 81, 21))
        self.checkBox_29.setAcceptDrops(True)
        self.checkBox_29.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_29.setObjectName("checkBox_29")
        self.label_12 = QtWidgets.QLabel(self.page_moshi)
        self.label_12.setGeometry(QtCore.QRect(30, 261, 81, 20))
        self.label_12.setStyleSheet("font: 14pt \"黑体\";")
        self.label_12.setObjectName("label_12")
        self.checkBox_32 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_32.setGeometry(QtCore.QRect(40, 60, 81, 21))
        self.checkBox_32.setAcceptDrops(True)
        self.checkBox_32.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkBox_37 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_37.setGeometry(QtCore.QRect(210, 290, 51, 21))
        self.checkBox_37.setAcceptDrops(True)
        self.checkBox_37.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_38.setGeometry(QtCore.QRect(280, 130, 81, 21))
        self.checkBox_38.setAcceptDrops(True)
        self.checkBox_38.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_31 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_31.setGeometry(QtCore.QRect(40, 290, 81, 21))
        self.checkBox_31.setAcceptDrops(True)
        self.checkBox_31.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_27 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_27.setGeometry(QtCore.QRect(130, 130, 81, 21))
        self.checkBox_27.setAcceptDrops(True)
        self.checkBox_27.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_27.setObjectName("checkBox_27")
        self.spinBox = QtWidgets.QSpinBox(self.page_moshi)
        self.spinBox.setGeometry(QtCore.QRect(390, 370, 42, 22))
        self.spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox.setObjectName("spinBox")
        self.checkBox_35 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_35.setGeometry(QtCore.QRect(130, 209, 81, 21))
        self.checkBox_35.setAcceptDrops(True)
        self.checkBox_35.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_28 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_28.setGeometry(QtCore.QRect(130, 60, 81, 21))
        self.checkBox_28.setAcceptDrops(True)
        self.checkBox_28.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_28.setObjectName("checkBox_28")
        self.label_13 = QtWidgets.QLabel(self.page_moshi)
        self.label_13.setGeometry(QtCore.QRect(30, 340, 81, 20))
        self.label_13.setStyleSheet("font: 14pt \"黑体\";")
        self.label_13.setObjectName("label_13")
        self.horizontalSlider = QtWidgets.QSlider(self.page_moshi)
        self.horizontalSlider.setGeometry(QtCore.QRect(130, 370, 221, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_11 = QtWidgets.QLabel(self.page_moshi)
        self.label_11.setGeometry(QtCore.QRect(30, 180, 61, 20))
        self.label_11.setStyleSheet("font: 14pt \"黑体\";")
        self.label_11.setObjectName("label_11")
        self.checkBox_25 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_25.setGeometry(QtCore.QRect(130, 290, 81, 21))
        self.checkBox_25.setAcceptDrops(True)
        self.checkBox_25.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_25.setObjectName("checkBox_25")
        self.label_14 = QtWidgets.QLabel(self.page_moshi)
        self.label_14.setGeometry(QtCore.QRect(40, 370, 81, 20))
        self.label_14.setStyleSheet("font: 14pt \"黑体\";")
        self.label_14.setObjectName("label_14")
        self.checkBox_36 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_36.setGeometry(QtCore.QRect(210, 130, 51, 21))
        self.checkBox_36.setAcceptDrops(True)
        self.checkBox_36.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_36.setObjectName("checkBox_36")
        self.label_9 = QtWidgets.QLabel(self.page_moshi)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 41, 21))
        self.label_9.setStyleSheet("font: 14pt \"黑体\";")
        self.label_9.setObjectName("label_9")
        self.checkBox_34 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_34.setGeometry(QtCore.QRect(40, 130, 81, 21))
        self.checkBox_34.setAcceptDrops(True)
        self.checkBox_34.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_33 = QtWidgets.QCheckBox(self.page_moshi)
        self.checkBox_33.setGeometry(QtCore.QRect(210, 209, 51, 21))
        self.checkBox_33.setAcceptDrops(True)
        self.checkBox_33.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_33.setObjectName("checkBox_33")
        self.stackedWidget.addWidget(self.page_moshi)
        self.page_printset = QtWidgets.QWidget()
        self.page_printset.setObjectName("page_printset")
        self.checkBox_52 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_52.setGeometry(QtCore.QRect(270, 40, 81, 21))
        self.checkBox_52.setAcceptDrops(True)
        self.checkBox_52.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_52.setObjectName("checkBox_52")
        self.label_16 = QtWidgets.QLabel(self.page_printset)
        self.label_16.setGeometry(QtCore.QRect(30, 80, 61, 21))
        self.label_16.setStyleSheet("font: 14pt \"黑体\";")
        self.label_16.setObjectName("label_16")
        self.checkBox_30 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_30.setGeometry(QtCore.QRect(100, 250, 61, 21))
        self.checkBox_30.setAcceptDrops(True)
        self.checkBox_30.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_30.setObjectName("checkBox_30")
        self.label_15 = QtWidgets.QLabel(self.page_printset)
        self.label_15.setGeometry(QtCore.QRect(30, 10, 81, 21))
        self.label_15.setStyleSheet("font: 14pt \"黑体\";")
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.page_printset)
        self.label_18.setGeometry(QtCore.QRect(30, 222, 81, 20))
        self.label_18.setStyleSheet("font: 14pt \"黑体\";")
        self.label_18.setObjectName("label_18")
        self.checkBox_48 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_48.setGeometry(QtCore.QRect(210, 110, 81, 21))
        self.checkBox_48.setAcceptDrops(True)
        self.checkBox_48.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_48.setObjectName("checkBox_48")
        self.label_23 = QtWidgets.QLabel(self.page_printset)
        self.label_23.setGeometry(QtCore.QRect(30, 282, 81, 20))
        self.label_23.setStyleSheet("font: 14pt \"黑体\";")
        self.label_23.setObjectName("label_23")
        self.checkBox_41 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_41.setGeometry(QtCore.QRect(130, 40, 81, 21))
        self.checkBox_41.setAcceptDrops(True)
        self.checkBox_41.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_54 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_54.setGeometry(QtCore.QRect(230, 310, 61, 21))
        self.checkBox_54.setAcceptDrops(True)
        self.checkBox_54.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_54.setObjectName("checkBox_54")
        self.label_24 = QtWidgets.QLabel(self.page_printset)
        self.label_24.setGeometry(QtCore.QRect(210, 340, 81, 20))
        self.label_24.setStyleSheet("font: 14pt \"黑体\";")
        self.label_24.setObjectName("label_24")
        self.checkBox_47 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_47.setGeometry(QtCore.QRect(40, 180, 61, 21))
        self.checkBox_47.setAcceptDrops(True)
        self.checkBox_47.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_47.setObjectName("checkBox_47")
        self.checkBox_55 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_55.setGeometry(QtCore.QRect(290, 310, 81, 21))
        self.checkBox_55.setAcceptDrops(True)
        self.checkBox_55.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_55.setObjectName("checkBox_55")
        self.checkBox_60 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_60.setGeometry(QtCore.QRect(40, 370, 61, 21))
        self.checkBox_60.setAcceptDrops(True)
        self.checkBox_60.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_60.setObjectName("checkBox_60")
        self.checkBox_40 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_40.setGeometry(QtCore.QRect(130, 110, 81, 21))
        self.checkBox_40.setAcceptDrops(True)
        self.checkBox_40.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_46 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_46.setGeometry(QtCore.QRect(40, 110, 61, 21))
        self.checkBox_46.setAcceptDrops(True)
        self.checkBox_46.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_46.setObjectName("checkBox_46")
        self.checkBox_58 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_58.setGeometry(QtCore.QRect(290, 370, 81, 21))
        self.checkBox_58.setAcceptDrops(True)
        self.checkBox_58.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_58.setObjectName("checkBox_58")
        self.label_21 = QtWidgets.QLabel(self.page_printset)
        self.label_21.setGeometry(QtCore.QRect(210, 220, 81, 20))
        self.label_21.setStyleSheet("font: 14pt \"黑体\";")
        self.label_21.setObjectName("label_21")
        self.checkBox_42 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_42.setGeometry(QtCore.QRect(130, 180, 81, 21))
        self.checkBox_42.setAcceptDrops(True)
        self.checkBox_42.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_44 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_44.setGeometry(QtCore.QRect(40, 40, 81, 21))
        self.checkBox_44.setAcceptDrops(True)
        self.checkBox_44.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_50 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_50.setGeometry(QtCore.QRect(210, 180, 81, 21))
        self.checkBox_50.setAcceptDrops(True)
        self.checkBox_50.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_50.setObjectName("checkBox_50")
        self.checkBox_56 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_56.setGeometry(QtCore.QRect(40, 310, 61, 21))
        self.checkBox_56.setAcceptDrops(True)
        self.checkBox_56.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_56.setObjectName("checkBox_56")
        self.checkBox_43 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_43.setGeometry(QtCore.QRect(40, 250, 61, 21))
        self.checkBox_43.setAcceptDrops(True)
        self.checkBox_43.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_53 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_53.setGeometry(QtCore.QRect(200, 40, 51, 21))
        self.checkBox_53.setAcceptDrops(True)
        self.checkBox_53.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_53.setObjectName("checkBox_53")
        self.label_22 = QtWidgets.QLabel(self.page_printset)
        self.label_22.setGeometry(QtCore.QRect(210, 280, 81, 20))
        self.label_22.setStyleSheet("font: 14pt \"黑体\";")
        self.label_22.setObjectName("label_22")
        self.checkBox_49 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_49.setGeometry(QtCore.QRect(230, 250, 61, 21))
        self.checkBox_49.setAcceptDrops(True)
        self.checkBox_49.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_49.setObjectName("checkBox_49")
        self.checkBox_51 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_51.setGeometry(QtCore.QRect(290, 250, 81, 21))
        self.checkBox_51.setAcceptDrops(True)
        self.checkBox_51.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_51.setObjectName("checkBox_51")
        self.checkBox_59 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_59.setGeometry(QtCore.QRect(100, 370, 61, 21))
        self.checkBox_59.setAcceptDrops(True)
        self.checkBox_59.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_59.setObjectName("checkBox_59")
        self.label_19 = QtWidgets.QLabel(self.page_printset)
        self.label_19.setGeometry(QtCore.QRect(30, 342, 81, 20))
        self.label_19.setStyleSheet("font: 14pt \"黑体\";")
        self.label_19.setObjectName("label_19")
        self.checkBox_45 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_45.setGeometry(QtCore.QRect(100, 310, 61, 21))
        self.checkBox_45.setAcceptDrops(True)
        self.checkBox_45.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_45.setObjectName("checkBox_45")
        self.checkBox_57 = QtWidgets.QCheckBox(self.page_printset)
        self.checkBox_57.setGeometry(QtCore.QRect(230, 370, 61, 21))
        self.checkBox_57.setAcceptDrops(True)
        self.checkBox_57.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_57.setObjectName("checkBox_57")
        self.label_17 = QtWidgets.QLabel(self.page_printset)
        self.label_17.setGeometry(QtCore.QRect(30, 150, 61, 20))
        self.label_17.setStyleSheet("font: 14pt \"黑体\";")
        self.label_17.setObjectName("label_17")
        self.stackedWidget.addWidget(self.page_printset)
        self.page_shuju = QtWidgets.QWidget()
        self.page_shuju.setObjectName("page_shuju")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.page_shuju)
        self.dateTimeEdit.setGeometry(QtCore.QRect(120, 90, 401, 51))
        self.dateTimeEdit.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(195, 195, 195);")
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 18), QtCore.QTime(12, 20, 0)))
        self.dateTimeEdit.setDate(QtCore.QDate(2021, 1, 18))
        self.dateTimeEdit.setTime(QtCore.QTime(12, 20, 0))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_20 = QtWidgets.QLabel(self.page_shuju)
        self.label_20.setGeometry(QtCore.QRect(80, 20, 151, 41))
        self.label_20.setStyleSheet("font: 14pt \"黑体\";")
        self.label_20.setObjectName("label_20")
        self.label_25 = QtWidgets.QLabel(self.page_shuju)
        self.label_25.setGeometry(QtCore.QRect(80, 190, 151, 41))
        self.label_25.setStyleSheet("font: 14pt \"黑体\";")
        self.label_25.setObjectName("label_25")
        self.spinBox_2 = QtWidgets.QSpinBox(self.page_shuju)
        self.spinBox_2.setGeometry(QtCore.QRect(150, 240, 81, 31))
        self.spinBox_2.setStyleSheet("font: 14pt \"黑体\";")
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_26 = QtWidgets.QLabel(self.page_shuju)
        self.label_26.setGeometry(QtCore.QRect(80, 280, 151, 41))
        self.label_26.setStyleSheet("font: 14pt \"黑体\";")
        self.label_26.setObjectName("label_26")
        self.checkBox_61 = QtWidgets.QCheckBox(self.page_shuju)
        self.checkBox_61.setGeometry(QtCore.QRect(210, 330, 61, 21))
        self.checkBox_61.setAcceptDrops(True)
        self.checkBox_61.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_61.setObjectName("checkBox_61")
        self.checkBox_62 = QtWidgets.QCheckBox(self.page_shuju)
        self.checkBox_62.setGeometry(QtCore.QRect(150, 330, 61, 21))
        self.checkBox_62.setAcceptDrops(True)
        self.checkBox_62.setStyleSheet("font: 13pt \"黑体\";")
        self.checkBox_62.setObjectName("checkBox_62")
        self.stackedWidget.addWidget(self.page_shuju)
        self.pushButton_moshi = QtWidgets.QPushButton(Form)
        self.pushButton_moshi.setGeometry(QtCore.QRect(190, 10, 81, 31))
        self.pushButton_moshi.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_moshi.setObjectName("pushButton_moshi")
        self.pushButton_qulv = QtWidgets.QPushButton(Form)
        self.pushButton_qulv.setGeometry(QtCore.QRect(100, 10, 81, 31))
        self.pushButton_qulv.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_qulv.setObjectName("pushButton_qulv")
        self.pushButton_quguangdu = QtWidgets.QPushButton(Form)
        self.pushButton_quguangdu.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.pushButton_quguangdu.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_quguangdu.setObjectName("pushButton_quguangdu")
        self.pushButton_data = QtWidgets.QPushButton(Form)
        self.pushButton_data.setGeometry(QtCore.QRect(370, 10, 81, 31))
        self.pushButton_data.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_data.setObjectName("pushButton_data")
        self.pushButton_xinxi = QtWidgets.QPushButton(Form)
        self.pushButton_xinxi.setGeometry(QtCore.QRect(460, 10, 81, 31))
        self.pushButton_xinxi.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_xinxi.setObjectName("pushButton_xinxi")
        self.pushButton_printset = QtWidgets.QPushButton(Form)
        self.pushButton_printset.setGeometry(QtCore.QRect(280, 10, 81, 31))
        self.pushButton_printset.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_printset.setObjectName("pushButton_printset")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_3.setText(_translate("Form", "13.5"))
        self.checkBox_5.setText(_translate("Form", "15.0"))
        self.label_3.setText(_translate("Form", "步长"))
        self.checkBox_8.setText(_translate("Form", "-"))
        self.checkBox_9.setText(_translate("Form", "12.0"))
        self.checkBox_4.setText(_translate("Form", "15.0"))
        self.label_2.setText(_translate("Form", "柱镜"))
        self.checkBox_15.setText(_translate("Form", "关闭"))
        self.label_4.setText(_translate("Form", "物像"))
        self.checkBox_10.setText(_translate("Form", "13.5"))
        self.checkBox_11.setText(_translate("Form", "0.0"))
        self.checkBox_2.setText(_translate("Form", "12.0"))
        self.label.setText(_translate("Form", "VD"))
        self.checkBox_16.setText(_translate("Form", "打开"))
        self.checkBox_7.setText(_translate("Form", "+/-"))
        self.checkBox.setText(_translate("Form", "0.0"))
        self.checkBox_6.setText(_translate("Form", "+"))
        self.checkBox_19.setText(_translate("Form", "标准"))
        self.checkBox_23.setText(_translate("Form", "0.05"))
        self.label_5.setText(_translate("Form", "模式"))
        self.checkBox_12.setText(_translate("Form", "0.12"))
        self.checkBox_26.setText(_translate("Form", "0.25"))
        self.checkBox_18.setText(_translate("Form", "平均"))
        self.checkBox_21.setText(_translate("Form", "半径"))
        self.label_8.setText(_translate("Form", "靶标范围"))
        self.checkBox_14.setText(_translate("Form", "1.332"))
        self.checkBox_17.setText(_translate("Form", "接近"))
        self.label_7.setText(_translate("Form", "折射率"))
        self.checkBox_22.setText(_translate("Form", "1.3375"))
        self.label_6.setText(_translate("Form", "步长"))
        self.checkBox_24.setText(_translate("Form", "1.336"))
        self.checkBox_20.setText(_translate("Form", "关闭"))
        self.checkBox_13.setText(_translate("Form", "度数"))
        self.checkBox_39.setText(_translate("Form", "30分"))
        self.label_10.setText(_translate("Form", "蜂鸣器"))
        self.checkBox_29.setText(_translate("Form", "REF"))
        self.label_12.setText(_translate("Form", "待机"))
        self.checkBox_32.setText(_translate("Form", "自动"))
        self.checkBox_37.setText(_translate("Form", "10分"))
        self.checkBox_38.setText(_translate("Form", "大"))
        self.checkBox_31.setText(_translate("Form", "关闭"))
        self.checkBox_27.setText(_translate("Form", "小"))
        self.checkBox_35.setText(_translate("Form", "KER"))
        self.checkBox_28.setText(_translate("Form", "手动"))
        self.label_13.setText(_translate("Form", "屏幕亮度"))
        self.label_11.setText(_translate("Form", "开机"))
        self.checkBox_25.setText(_translate("Form", "5分"))
        self.label_14.setText(_translate("Form", "亮度："))
        self.checkBox_36.setText(_translate("Form", "中"))
        self.label_9.setText(_translate("Form", "测量"))
        self.checkBox_34.setText(_translate("Form", "关闭"))
        self.checkBox_33.setText(_translate("Form", "K R"))
        self.checkBox_52.setText(_translate("Form", "100%"))
        self.label_16.setText(_translate("Form", "屈光"))
        self.checkBox_30.setText(_translate("Form", "打开"))
        self.label_15.setText(_translate("Form", "打印浓度"))
        self.label_18.setText(_translate("Form", "自动"))
        self.checkBox_48.setText(_translate("Form", "平均"))
        self.label_23.setText(_translate("Form", "打印清除"))
        self.checkBox_41.setText(_translate("Form", "80%"))
        self.checkBox_54.setText(_translate("Form", "关闭"))
        self.label_24.setText(_translate("Form", "基弧"))
        self.checkBox_47.setText(_translate("Form", "关闭"))
        self.checkBox_55.setText(_translate("Form", "打开"))
        self.checkBox_60.setText(_translate("Form", "关闭"))
        self.checkBox_40.setText(_translate("Form", "标准"))
        self.checkBox_46.setText(_translate("Form", "关闭"))
        self.checkBox_58.setText(_translate("Form", "打开"))
        self.label_21.setText(_translate("Form", "图形"))
        self.checkBox_42.setText(_translate("Form", "标准"))
        self.checkBox_44.setText(_translate("Form", "70%"))
        self.checkBox_50.setText(_translate("Form", "平均"))
        self.checkBox_56.setText(_translate("Form", "关闭"))
        self.checkBox_43.setText(_translate("Form", "关闭"))
        self.checkBox_53.setText(_translate("Form", "90%"))
        self.label_22.setText(_translate("Form", "SE"))
        self.checkBox_49.setText(_translate("Form", "关闭"))
        self.checkBox_51.setText(_translate("Form", "打开"))
        self.checkBox_59.setText(_translate("Form", "打开"))
        self.label_19.setText(_translate("Form", "瞳孔直径"))
        self.checkBox_45.setText(_translate("Form", "打开"))
        self.checkBox_57.setText(_translate("Form", "关闭"))
        self.label_17.setText(_translate("Form", "曲率"))
        self.label_20.setText(_translate("Form", "日期/时间"))
        self.label_25.setText(_translate("Form", "计数"))
        self.label_26.setText(_translate("Form", "自动计数"))
        self.checkBox_61.setText(_translate("Form", "打开"))
        self.checkBox_62.setText(_translate("Form", "关闭"))
        self.pushButton_moshi.setText(_translate("Form", "模式"))
        self.pushButton_qulv.setText(_translate("Form", "曲率"))
        self.pushButton_quguangdu.setText(_translate("Form", "屈光度"))
        self.pushButton_data.setText(_translate("Form", "数据"))
        self.pushButton_xinxi.setText(_translate("Form", "信息传送"))
        self.pushButton_printset.setText(_translate("Form", "打印设置"))

